# Generated by Django 4.0.4 on 2022-06-06 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voteid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='mysite.voteid'),
        ),
    ]
