# Generated by Django 4.0.4 on 2022-06-10 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_idcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteid',
            name='idcard',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.idcard'),
        ),
    ]
