# Generated by Django 4.0.4 on 2022-06-10 11:22

from django.db import migrations

def set_voteids_idcard(apps, schema_editor):
    IDCard = apps.get_model("mysite", "IDCard")
    VoteID = apps.get_model("mysite", "VoteID")

    for voteid in VoteID.objects.filter(idcard__isnull=True):
        idcard = None
        queryset = IDCard.objects.filter(number=voteid.idcard_num)

        if queryset.exists():
            idcard = queryset.first()
        else:
            idcard = IDCard.objects.create(number=voteid.idcard_num)
        
        voteid.idcard = idcard
        voteid.save()

class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_voteid_idcard'),
    ]

    operations = [
        migrations.RunPython(set_voteids_idcard)
    ]
