# Generated by Django 4.0.4 on 2022-05-23 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('given_names', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=5)),
                ('height', models.FloatField()),
                ('occupation', models.CharField(max_length=100)),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fathered_children', to='identification_api.person')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mothered_children', to='identification_api.person')),
            ],
        ),
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_issue', models.DateField(auto_now_add=True)),
                ('date_of_expiration', models.DateField()),
                ('identification_post', models.CharField(max_length=10)),
                ('unique_identifier', models.CharField(max_length=100, unique=True)),
                ('number', models.CharField(max_length=100)),
                ('sm', models.CharField(max_length=6)),
                ('signature', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('fingerprint', models.ImageField(upload_to='')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identification_api.person')),
            ],
        ),
    ]
