# Generated by Django 4.0.4 on 2022-05-23 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identification_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='father',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fathered_children', to='identification_api.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mother',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mothered_children', to='identification_api.person'),
        ),
    ]
